safe: true
lsi: false
pygments: true

exclude: ['README.md', 'config.rb', '*.sln', '*.suo', '*.config', 'docs']

domain: accord.github.io
title: Accord.NET Framework



google_analytics:
  account: UA-3114672-4

github:
  username: cesarsouza

disqus:
  id: accord-net

framework:
  version: v2.10
  download-installer: https://github.com/accord-net/framework/releases/download/v2.10.0/Accord.NET.Framework-2.10.0.exe
  download-archive:   https://github.com/accord-net/framework/releases/download/v2.10.0/Accord.NET.Framework-2.10.0.rar
