safe: true
lsi: false
pygments: true

exclude: ['README.md', 'config.rb', '*.sln', '*.suo', '*.config']

domain: accord-framework.net
title: Accord.NET Machine Learning Framework


gems:
  - jekyll-sitemap

google_analytics:
  account: UA-3114672-6

github:
  username: cesarsouza

disqus:
  id: accord-net

framework:
  version: v2.13
  download-installer: https://github.com/accord-net/framework/releases/download/v2.13.1/Accord.NET-2.13.1-installer.exe
  download-archive:   https://github.com/accord-net/framework/releases/download/v2.13.1/Accord.NET-2.13.1-archive.rar
