safe: true
lsi: false
pygments: true

exclude: ['README.md', 'config.rb', '*.sln', '*.suo', '*.config']

domain: accord-framework.net
title: Accord.NET Framework



google_analytics:
  account: UA-3114672-6

github:
  username: cesarsouza

disqus:
  id: accord-net

framework:
  version: v2.13
  download-installer: https://github.com/accord-net/framework/releases/download/v2.13.0/Accord.NET-2.13.0-installer.rar
  download-archive:   https://github.com/accord-net/framework/releases/download/v2.13.0/Accord.NET-2.13.0-archive.rar
